config/routes.rb
Rails.application.routes.draw do
  root to: 'app/front#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  namespace :app, path: '/' do
    post '/inmuebles', to: 'properties#search', as: 'search'
    resources :properties, path: '/inmuebles',
              param: :code, only: [:index, :show] do
      resources :questions, only: :create
    end
  end

  namespace :admin do
    resources :customers do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :properties do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
      resources :questions do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete(
          action: :destroy_multiple,
          on: :collection,
          as: :destroy_multiple
        )
      end
    end

    root to: 'admin#root'

    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :meta_tags do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_adwords do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_analytics_tracks do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :settings, only: [] do
      collection do
        get '/:config', to: 'settings#edit', as: ''
        put '/:config', to: 'settings#update', as: 'update'
      end
    end
  end

  # Errors routes
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Dashboard route engine
  mount KepplerGaDashboard::Engine, at: 'admin/dashboard', as: 'dashboard'
  mount KepplerContactUs::Engine, at: '/', as: 'messages'
end

app/models/meta_tag.rb
# MetaTag Model
class MetaTag < ActiveRecord::Base
  include ElasticSearchable
  include ActivityHistory

  def self.query(query)
    { query: { multi_match: {
      query: query,
      fields: [:title, :description, :url],
      operator: :and,
      lenient: true }
    }, sort: { id: 'desc' }, size: count }
  end

  def self.get_by_url(url)
    find_by_url(url)
  end

  # Build index elasticsearch
  def as_indexed_json(_options = {})
    as_json(
      only: [:id, :title, :description, :url]
    )
  end
end

app/controllers/admin/meta_tags_controller.rb
module Admin
  # MetaTagController
  class MetaTagsController < AdminController
    before_action :set_meta_tag, only: [:show, :edit, :update, :destroy]
    before_action :show_history, only: [:index]

    # GET /meta_tags
    def index
      meta_tags = MetaTag.searching(@query).all
      @objects = meta_tags.page(@current_page)
      @total = meta_tags.size
      if !@objects.first_page? && @objects.size.zero?
        redirect_to meta_tags_path(
          page: @current_page.to_i.pred, search: @query
        )
      end
    end

    # GET /meta_tags/1
    def show
    end

    # GET /meta_tags/new
    def new
      @meta_tag = MetaTag.new
    end

    # GET /meta_tags/1/edit
    def edit
    end

    # POST /meta_tags
    def create
      @meta_tag = MetaTag.new(meta_tag_params)

      if @meta_tag.save
        redirect(@meta_tag, params)
      else
        render :new
      end
    end

    # PATCH/PUT /meta_tags/1
    def update
      if @meta_tag.update(meta_tag_params)
        redirect(@meta_tag, params)
      else
        render :edit
      end
    end

    # DELETE /meta_tags/1
    def destroy
      @meta_tag.destroy
      redirect_to admin_meta_tags_path, notice: actions_messages(@meta_tag)
    end

    def destroy_multiple
      MetaTag.destroy redefine_ids(params[:multiple_ids])
      redirect_to(
        admin_meta_tags_path(page: @current_page, search: @query),
        notice: actions_messages(MetaTag.new)
      )
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_meta_tag
      @meta_tag = MetaTag.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def meta_tag_params
      params.require(:meta_tag).permit(:title, :description, :meta_tags, :url)
    end

    def show_history
      get_history(MetaTag)
    end
  end
end

app/views/admin/meta_tags/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.code.css_class("md-light")
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		.collection.with-header
			.collection-header
				%h5
					= t("keppler.titles.history")
			- @activities.each do |activity|
				- if activity.trackable_type.eql? "Session"
					= render partial: "public_activity/session/#{activity.key.split(".").second}", locals: { activity: activity, method: "title" }
				- else
					= render partial: "public_activity/layout/#{activity.key.split(".").second}", locals: { activity: activity, method: "title" }

app/views/admin/meta_tags/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to admin_meta_tags_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				.card-content
					= simple_form_for [:admin, @meta_tag] do |f|
						.row
							.preview
							= f.input :url
							= f.input :title
							= f.input :description, input_html: { class: "materialize-textarea" }
							= f.input :meta_tags, input_html: { class: "materialize-textarea" }

							.form-actions.right
								= f.button :submit, t("keppler.actions.save"), name: "_save"
								= f.button :submit, t("keppler.actions.save_and_add_another"), name: "_add_other"

app/views/admin/meta_tags/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, MetaTag
			= link_to edit_admin_meta_tag_path(@meta_tag), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.edit") do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.code.css_class("md-light")
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.card-content
		%ul.list
			%li.list-row
				.display-label= t("activerecord.attributes.meta_tag.title")
				.display-value= @meta_tag.title
			%li.list-row
				.display-label= t("activerecord.attributes.meta_tag.description")
				.display-value= @meta_tag.description
			%li.list-row
				.display-label= t("activerecord.attributes.meta_tag.meta_tags")
				.display-value= @meta_tag.meta_tags
			%li.list-row
				.display-label= t("activerecord.attributes.meta_tag.url")
				.display-value= @meta_tag.url

			%li.list-row
				= link_to t('keppler.actions.back_history'), admin_meta_tags_path

:javascript
	$('.tooltipped').tooltip({delay: 1});

app/views/admin/meta_tags/_listing.html.haml
%tr{ id: "row-#{meta_tag.id}" }
	- if can? :destroy_multiple, MetaTag
		%td.item-check{style:"width: 10%"}
			= link_to "", admin_meta_tag_path(meta_tag), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{meta_tag.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{meta_tag.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{meta_tag.id}" }

		%td{style:"width: 30%"}
			= link_to "", admin_meta_tag_path(meta_tag, search: @query), remote: true, class: "show-row"
			%span
				= meta_tag.title
		%td{style:"width: 30%"}
			= link_to "", admin_meta_tag_path(meta_tag, search: @query), remote: true, class: "show-row"
			%span
				= meta_tag.url

	%td{style:"width: 5%"}
		= link_to admin_meta_tag_path(meta_tag), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/admin/meta_tags/edit.html.haml
= title(t('keppler.titles.edit', model: "Meta tags"))
= render 'form'

app/views/admin/meta_tags/index.html.haml
= title(t('keppler.titles.index', model: "Meta tags"))
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_admin_meta_tag_path, class: "btn-add btn-floating btn-large waves-effect waves-light btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |meta_tag|
				= render 'listing', meta_tag: meta_tag
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							= t('keppler.messages.not_found_records', model:  t("keppler.models.pluralize.meta_tags"))
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_admin_meta_tag_path, class: "btn-add btn-index-add btn-floating btn-large waves-effect waves-light" do
		= material_icon.md_24.add.css_class("md-light")

app/views/admin/meta_tags/new.html.haml
= title(t('keppler.titles.new', model: "Meta tags"))
= render 'form'

app/views/admin/meta_tags/show.html.haml
= title(t('keppler.titles.show', model: "Meta tags"))
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, MetaTag
				= link_to admin_meta_tag_path(@meta_tag), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.delete"), method: :delete, data: { confirm: t("keppler.messages.data_confirm") } do
					= material_icon.md_18.delete.css_class("md-dark")
			- if can? :update, MetaTag
				= link_to edit_admin_meta_tag_path(@meta_tag), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" =>t("keppler.actions.edit") do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to admin_meta_tags_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.card
			.card-content
				%ul.list
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.id")
						.display-value.fs-body-1.tc-black-2= @meta_tag.id.to_s.humanize
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.title")
						.display-value.fs-body-1.tc-black-2= @meta_tag.title.to_s.humanize
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.description")
						.display-value.fs-body-1.tc-black-2= @meta_tag.description.to_s.humanize
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.meta_tags")
						.display-value.fs-body-1.tc-black-2= @meta_tag.meta_tags.to_s.humanize
					%li.list-row
						.display-label= t("activerecord.attributes.#{controller_name.singularize}.url")
						.display-value.fs-body-1.tc-black-2= @meta_tag.url.to_s.humanize

app/views/admin/meta_tags/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@meta_tag.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");