config/routes.rb
Rails.application.routes.draw do
  root to: 'app/front#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  namespace :app, path: '/' do
    post '/inmuebles', to: 'properties#search', as: 'search'
    resources :properties, path: '/inmuebles',
              param: :code, only: [:index, :show] do
      resources :questions, only: :create
    end
  end

  namespace :admin do
    resources :customers do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :properties do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
      resources :questions do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete(
          action: :destroy_multiple,
          on: :collection,
          as: :destroy_multiple
        )
      end
    end

    root to: 'admin#root'

    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :meta_tags do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_adwords do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_analytics_tracks do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :settings, only: [] do
      collection do
        get '/:config', to: 'settings#edit', as: ''
        put '/:config', to: 'settings#update', as: 'update'
      end
    end
  end

  # Errors routes
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Dashboard route engine
  mount KepplerGaDashboard::Engine, at: 'admin/dashboard', as: 'dashboard'
  mount KepplerContactUs::Engine, at: '/', as: 'messages'
end

app/models/customer.rb
# Customer Model
class Customer < ActiveRecord::Base
  include ElasticSearchable
  include ActivityHistory
  mount_uploader :image, AttachmentUploader
  validates_uniqueness_of :name
  validates_presence_of :name, :image

  def self.query(query)
    { query: { multi_match: {
      query: query,
      fields: [:name, :image],
      operator: :and,
      lenient: true }
    }, sort: { id: 'desc' }, size: count }
  end

  # Build index elasticsearch
  def as_indexed_json(_options = {})
    as_json(
      only: [:id, :name, :image]
    )
  end
end

app/controllers/admin/customers_controller.rb
module Admin
  # CustomersController
  class CustomersController < AdminController
    before_action :set_customer, only: [:show, :edit, :update, :destroy]
    before_action :show_history, only: [:index]

    # GET /customers
    def index
      customers = Customer.searching(@query).all
      @objects = customers.page(@current_page)
      @total = customers.size
      if !@objects.first_page? && @objects.size.zero?
        redirect_to customers_path(page: @current_page.to_i.pred, search: @query)
      end
    end

    # GET /customers/1
    def show
    end

    # GET /customers/new
    def new
      @customer = Customer.new
    end

    # GET /customers/1/edit
    def edit
    end

    # POST /customers
    def create
      @customer = Customer.new(customer_params)

      if @customer.save
        redirect(@customer, params)
      else
        render :new
      end
    end

    # PATCH/PUT /customers/1
    def update
      if @customer.update(customer_params)
        redirect(@customer, params)
      else
        render :edit
      end
    end

    # DELETE /customers/1
    def destroy
      @customer.destroy
      redirect_to admin_customers_path, notice: actions_messages(@customer)
    end

    def destroy_multiple
      Customer.destroy redefine_ids(params[:multiple_ids])
      redirect_to(
        admin_customers_path(page: @current_page, search: @query),
        notice: actions_messages(Customer.new)
      )
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def customer_params
      params.require(:customer).permit(:name, :image)
    end

    def show_history
      get_history(Customer)
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class('md-light')
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: 'height: {{windowHeight}}px;' }
	.list
		.collection.with-header
			.collection-header
				%h5
					= t('keppler.titles.history')
			- @activities.each do |activity|
				- if activity.trackable_type.eql? 'Session'
					= render partial: "public_activity/session/#{activity.key.split(".").second}", locals: { activity: activity, method: 'id' }
				- else
					= render partial: "public_activity/layout/#{activity.key.split(".").second}", locals: { activity: activity, method: 'id' }

app/views/admin/customers/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to admin_customers_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				.card-content
					= simple_form_for [:admin, @customer] do |f|
						.row
							= f.input :name
							= f.input :image, as: :file_material, label: false, wrapper_html: { class: "file-field" }

							.form-actions.right
								= f.button :submit, t("keppler.actions.save"), name: '_save'
								= f.button :submit, t("keppler.actions.save_and_add_another"), name: '_add_other'

app/views/admin/customers/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Customer
			= link_to edit_admin_customer_path(@customer), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.edit") do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light")
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.card-image{ style: 'padding: 25px;' }
		= image_tag @customer.image
	.card-content
		%ul.list
			%li.list-row{style: 'text-align: center;'}
				.display-label= @customer.name
			%li.list-row
				= link_to t('keppler.actions.back_history'), admin_customers_path

:javascript
	$('.tooltipped').tooltip({delay: 1});

app/views/admin/customers/_listing.html.haml
%tr{ id: "row-#{customer.id}" }
	- if can? :destroy_multiple, Customer
		%td.item-check{style:"width: 10%"}
			= link_to "", admin_customer_path(customer), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{customer.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{customer.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{customer.id}" }

		%td{style:"width: 30%"}
			= link_to "", admin_customer_path(customer, search: @query), remote: true, class: "show-row"
			%span
				= customer.name
	%td{style:"width: 5%"}
		= link_to admin_customer_path(customer), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/admin/customers/edit.html.haml
= title(t('keppler.titles.edit', model: "Customers"))
= render 'form'

app/views/admin/customers/index.html.haml
= title(t('keppler.titles.index', model: "Customers"))
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_admin_customer_path, class: "btn-floating btn-large waves-effect waves-light btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |customer|
				= render 'listing', customer: customer
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							= t('keppler.messages.not_found_records', model:  t("keppler.models.pluralize.customers"))
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_admin_customer_path, class: "btn-index-add btn-floating btn-large waves-effect waves-light" do
		= material_icon.md_24.add.css_class("md-light")

app/views/admin/customers/new.html.haml
= title(t('keppler.titles.new', model: "Customers"))
= render 'form'

app/views/admin/customers/show.html.haml
= title(t('keppler.titles.show', model: "Customers"))
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Customer
				= link_to admin_customer_path(@customer), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.delete"), method: :delete, data: { confirm: t("keppler.messages.data_confirm") } do
					= material_icon.md_18.delete.css_class("md-dark")
			- if can? :update, Customer
				= link_to edit_admin_customer_path(@customer), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" =>t("keppler.actions.edit") do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to admin_customers_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.card
			.card-content#customer-label
				.display-label{ style: 'text-align: center;' }= @customer.name.to_s.humanize
			.card-image
				= image_tag @customer.image, id: 'customer-img'

app/views/admin/customers/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@customer.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");