config/routes.rb
Rails.application.routes.draw do
  root to: 'app/front#index'

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  namespace :app, path: '/' do
    post '/inmuebles', to: 'properties#search', as: 'search'
    resources :properties, path: '/inmuebles',
              param: :code, only: [:index, :show] do
      resources :questions, only: :create
    end
  end

  namespace :admin do
    resources :customers do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :properties do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
      resources :questions do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete(
          action: :destroy_multiple,
          on: :collection,
          as: :destroy_multiple
        )
      end
    end

    root to: 'admin#root'

    resources :users do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :meta_tags do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_adwords do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :google_analytics_tracks do
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete(
        '/destroy_multiple',
        action: :destroy_multiple,
        on: :collection,
        as: :destroy_multiple
      )
    end

    resources :settings, only: [] do
      collection do
        get '/:config', to: 'settings#edit', as: ''
        put '/:config', to: 'settings#update', as: 'update'
      end
    end
  end

  # Errors routes
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Dashboard route engine
  mount KepplerGaDashboard::Engine, at: 'admin/dashboard', as: 'dashboard'
  mount KepplerContactUs::Engine, at: '/', as: 'messages'
end

app/models/property.rb
# Property Model
class Property < ActiveRecord::Base
  include ElasticSearchable
  include ActivityHistory
  has_many :images, dependent: :destroy
  has_many :questions, dependent: :destroy
  enum property_type: [:casa, :apartamento, :terreno, :edificio, :local]
  enum operation_type: [:venta, :alquiler]
  accepts_nested_attributes_for :images,
                                reject_if: :all_blank,
                                allow_destroy: true

  # Validations
  validates_presence_of :property_type, :code, :city, :zone, :size,
                        :reference, :operation_type, :price
  validates_uniqueness_of :code
  validates :images, presence: true, on: [:update, :create]
  validates :images, length: { maximum: 4 }
  validates :price, numericality: { greater_than: 0 }
  validates :price, numericality: { greater_than: 0 }
  validates :size, numericality: { greater_than: 0 }
  validates :rooms, numericality: { greater_than_or_equal_to: 0 }, allow_blank: true
  validates :bathrooms, numericality: { greater_than_or_equal_to: 0 }, allow_blank: true

  validate :images_present?, on: [:update, :create]

  def self.reload_index!
    __elasticsearch__.delete_index!
    __elasticsearch__.create_index!
    __elasticsearch__.import
  end

  settings analysis: {
    analyzer: {
      spanish_snowball: {
        type: 'snowball',
        language: 'Spanish',
        filter: %w(asciifolding lowercase)
      },
      autocomplete: {
        type:      'custom',
        tokenizer: 'standard',
        filter: %w(lowercase autocomplete_filter)
      }
    },
    filter: {
      autocomplete_filter: {
        type: 'edge_ngram',
        min_gram: 1,
        max_gram: 20
      }
    }
  } do
    mapping do
      [:id, :property_type, :code, :city, :zone,
       :reference, :operation_type, :price, :rooms,
       :bathrooms, :size, :description].each do |attribute|
        indexes attribute, type: 'string', analyzer: 'spanish_snowball'
      end
    end
  end

  def self.query(query)
    { query: { multi_match: {
      query: query,
      fields: [:property_type, :code, :city, :zone, :reference, :operation_type,
               :price, :rooms, :bathrooms, :size, :description],
      operator: :and,
      lenient: true }
    }, sort: { id: 'desc' }, size: count }
  end


  def self.app_searching(query)
    if query
      search(app_query(query)).records.order(id: :desc)
    else
      order(id: :desc)
    end
  end

  def self.app_query(query)
    {
      query: {
        bool: {
          should: [{
            match:  {
              _all: {
                query: query,
                fuzziness: 'auto'
              }
            }
          }]
        }
      }, size: count
    }
  end

  # Get the page number that the object belongs to
  def page(order = :id)
    ((self.class.order(order => :desc)
      .pluck(order).index(send(order)) + 1)
        .to_f / 3).ceil
  end

  # Build index elasticsearch
  def as_indexed_json(_options = {})
    as_json(
      only: [:id, :property_type, :code, :city, :zone,
             :reference, :operation_type, :price, :rooms,
             :bathrooms, :size, :description]
    )
  end

  def images_present?
    errors.add(:images, 'Debe agregar imágenes') if images.empty?
  end

  def unread_questions
    unread = questions.where(read: false).count
    unread > 0 ? "Preguntas (#{unread} sin leer)" : 'Preguntas'
  end

  def questions_class
    questions.where(read: false).any? ? 'keppler' : 'md-dark'
  end

  def rooms_text
    "#{rooms} Habitaciones"
  end

  def bathrooms_text
    "#{bathrooms} Baños"
  end

  def search_similar
    "#{zone} #{city} #{property_type}"
  end
end

app/controllers/admin/properties_controller.rb
module Admin
  # PropertiesController
  class PropertiesController < AdminController
    before_action :set_property, only: [:show, :edit, :update, :destroy, :edit_room_images, :update_room_images,]
    before_action :show_history, only: [:index]

    # GET /properties
    def index
      properties = Property.searching(@query).all
      @objects = properties.page(@current_page)
      @total = properties.size
      if !@objects.first_page? && @objects.size.zero?
        redirect_to properties_path(page: @current_page.to_i.pred, search: @query)
      end
    end

    # GET /properties/1
    def show
      @property = @property.decorate
    end

    # GET /properties/new
    def new
      @property = Property.new
      @property_types = Property.property_types.transform_keys { |x| x.humanize }
      @operation_types = Property.operation_types.transform_keys { |x| x.humanize }
    end

    # GET /properties/1/edit
    def edit
    end

    # POST /properties
    def create
      @property = Property.new(property_params)

      if @property.save
        redirect(@property, params)
      else
        render :new
      end
    end

    # PATCH/PUT /properties/1
    def update
      if @property.update(property_params)
        redirect(@property, params)
      else
        if @property.errors.messages[:images]
          if @property.errors.messages[:images].first == 'is too long (maximum is 4 characters)'
            @property.errors.messages[:images] = ['Deben ser máximo 4 Imágenes']
          end
        end
        render :edit
      end
    end

    # DELETE /properties/1
    def destroy
      @property.destroy
      redirect_to admin_properties_path, notice: actions_messages(@property)
    end

    def destroy_multiple
      Property.destroy redefine_ids(params[:multiple_ids])
      redirect_to(
        admin_properties_path(page: @current_page, search: @query),
        notice: actions_messages(Property.new)
      )
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def property_params
      params.require(:property)
            .permit(:property_type, :code, :city, :zone, :reference,
                    :operation_type, :price, :rooms, :bathrooms, :size,
                    :description, images_attributes: [:id, :img, :_destroy])
    end

    def show_history
      get_history(Property)
    end
  end
end

app/controllers/app/properties_controller.rb
module App
  # PropertiesController
  class PropertiesController < AppController
    before_filter :paginator_params, on: :index

    def index
      properties = Property.searching(@query).all
      @properties = properties.page(@current_page).per(6)
      @total = properties.size
      if !@properties.first_page? && @properties.size.zero?
        redirect_to properties_path(page: @current_page.to_i.pred, search: @query)
      end
    end

    def search
      properties = Property.searching(@query).all
      @properties = properties.page(@current_page).per(6)
      @total = properties.size
      if !@properties.first_page? && @properties.size.zero?
        redirect_to properties_path(page: @current_page.to_i.pred, search: @query)
      end
    end

    def show
      @property = Property.find_by code: params[:code]
      @question = Question.new

      @suggestions = Property.app_searching(@property.search_similar)
      @suggestions = limit_suggestions @suggestions
    end

    def paginator_params
      @query = params[:search] unless params[:search].blank?
      @current_page = params[:page] unless params[:page].blank?
    end

    def limit_suggestions(properties)
      properties.where.not(id: @property.id).limit 3
    end
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/admin/properties/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.account_circle.css_class('md-light')
		Inmueble
.listing-show-body.card{ resize: true , style: 'height: {{windowHeight}}px;' }
	.list
		.collection.with-header
			.collection-header
				%h5
					= t('keppler.titles.history')
			- @activities.each do |activity|
				- if activity.trackable_type.eql? 'Session'
					= render partial: "public_activity/session/#{activity.key.split(".").second}", locals: { activity: activity, method: 'id' }
				- else
					= render partial: "public_activity/layout/#{activity.key.split(".").second}", locals: { activity: activity, method: 'id' }

app/views/admin/properties/_form.html.haml
.wrapper
  .wrapper-body.container
    .actions
      = link_to admin_properties_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
        = material_icon.md_18.arrow_back.css_class("md-dark")
    .wrapper-inputs
      .card
        .card-content
          = simple_form_for [:admin, @property] do |f|
            .row
              = f.input :property_type, collection: [['Casa', 'casa'], ['Apartamento', 'apartamento'], ['Terreno','terreno'], ['Local', 'local'], ['Edificio', 'edificio']], prompt:'Elegir tipo de propiedad'
              = f.input :operation_type, collection: [['Alquiler', 'alquiler'],['Venta', 'venta']], prompt:'Elegir tipo de operación'
              = f.input :code
              = f.input :city
              = f.input :zone
              = f.input :reference, input_html: {class: "materialize-textarea"}
              = f.input :description, input_html: {class: "materialize-textarea"}
              = f.input :price
              = f.input :rooms
              = f.input :bathrooms
              = f.input :size
            .row
              - if @property.errors && @property.errors.messages[:images]
                .input-field.col.s12.error
                  %span.help-inline= @property.errors.messages[:images].first

              = f.simple_fields_for :images do |c|
                = render 'image_fields', :f => c
              .form-actions.right
                = link_to_add_association 'Agregar Imagen', f, :images, class: "waves-effect waves-dark btn-flat"

                = f.button :submit, t("keppler.actions.save"), name: '_save'
                = f.button :submit, t("keppler.actions.save_and_add_another"), name: '_add_other'

app/views/admin/properties/_image_fields.html.haml
.nested-fields.col.s12
  %ul.collection
    %li.collection-item.avatar
      %img.circle{:src => "#{f.object.img.thumb unless f.object.img.to_s == ''}", id: "circle-#{f.object.id}"}
        = f.input :img, :as => :file_material, label: false, wrapper_html: { class: "file-field input-#{f.object.id}"}
        .secondary-content
          = link_to_remove_association f do
            = material_icon.md_24.close.css_class('md-dark')
        :javascript
          src = $('#circle-#{f.object.id}').attr('src').split('thumb_')[1]
          $('.input-#{f.object.id}').find('.file-path').val(src)

app/views/admin/properties/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Property
			= link_to edit_admin_property_path(@property), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.edit") do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.account_circle.css_class("md-light")
		Inmueble
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	- if @property.images.any?
		= image_tag @property.images.first.img
	.card-content
		%ul.list
			%li.list-row
				.display-label= t("activerecord.attributes.property.code")
				.display-value= @property.code
			%li.list-row
				.display-label= t("activerecord.attributes.property.property_type")
				.display-value= "#{@property.property_type.humanize} de #{@property.size}"
			%li.list-row
				.display-label= t("activerecord.attributes.property.city")
				.display-value= @property.city.humanize
			%li.list-row
				.display-label= t("activerecord.attributes.property.operation_type")
				.display-value= @property.operation_type.humanize
			%li.list-row
				.display-label= t("activerecord.attributes.property.price")
				.display-value= @property.price
			%li.list-row
				.display-label
					= t("activerecord.attributes.property.rooms") + ' / '
					= t("activerecord.attributes.property.bathrooms")
				.display-value
					= "#{@property.rooms} / #{@property.bathrooms}"
			%li.list-row
				.display-label= t("activerecord.attributes.property.description")
				.display-value= @property.description
			%li.list-row
				= link_to t('keppler.actions.back_history'), admin_properties_path

:javascript
	$('.tooltipped').tooltip({delay: 1});

app/views/admin/properties/_listing.html.haml
%tr{ id: "row-#{property.id}" }
	- if can? :destroy_multiple, Property
		%td.item-check{style:"width: 10%"}
			= link_to "", admin_property_path(property), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{property.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{property.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{property.id}" }

		%td{style:"width: 10%"}
			= link_to "", admin_property_path(property, search: @query), remote: true, class: "show-row"
			%span
				= property.code
		%td{style:"width: 30%"}
			= link_to "", admin_property_path(property, search: @query), remote: true, class: "show-row"
			%span
				= property.operation_type.humanize
		%td{style:"width: 30%"}
			= link_to "", admin_property_path(property, search: @query), remote: true, class: "show-row"
			%span
				= property.price
		%td{style:"width: 30%"}
			= link_to "", admin_property_path(property, search: @query), remote: true, class: "show-row"
			%span
				= property.city.humanize
		%td{style:"width: 30%"}
			= link_to admin_property_questions_path(property), class: "btn-floating waves-effect btn-flat tooltipped", "data-position" => "top", "data-tooltip" => property.unread_questions do
				= material_icon.md_24.live_help.css_class(property.questions_class)
	%td{style:"width: 5%"}
		= link_to admin_property_path(property), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/admin/properties/edit.html.haml
= title(t('keppler.titles.edit', model: "Inmuebles"))
= render 'form'

app/views/admin/properties/index.html.haml
= title(t('keppler.titles.index', model: "Inmuebles"))
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_admin_property_path, class: "btn-floating btn-large waves-effect waves-light btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |property|
				= render 'listing', property: property.decorate
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							= t('keppler.messages.not_found_records', model:  t("keppler.models.pluralize.properties"))
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_admin_property_path, class: "btn-index-add btn-floating btn-large waves-effect waves-light" do
		= material_icon.md_24.add.css_class("md-light")

app/views/admin/properties/new.html.haml
= title(t('keppler.titles.new', model: "Inmuebles"))
= render 'form'

app/views/admin/properties/show.html.haml
= title(t('keppler.titles.show', model: "Inmuebles"))
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Property
				= link_to admin_property_path(@property), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.delete"), method: :delete, data: { confirm: t("keppler.messages.data_confirm") } do
					= material_icon.md_18.delete.css_class("md-dark")
			- if can? :update, Property
				= link_to edit_admin_property_path(@property), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" =>t("keppler.actions.edit") do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to admin_properties_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => t("keppler.actions.back") do
				= material_icon.md_18.arrow_back.css_class("md-dark")
			= link_to admin_property_questions_path(@property), class: "right btn-floating waves-effect btn-flat tooltipped", "data-position" => "top", "data-tooltip" => @property.unread_questions do
				= material_icon.md_24.live_help.css_class(@property.questions_class)
		.card#show-property
			- if @property.images.any?
				.card-image
					.slider
						%ul.slides
							- @property.images.each do |item|
								%li
									= image_tag item.img

			.card-content
				%table.table.table-bordered
					%tr
						%th= t("activerecord.attributes.property.property_type")
						%th= t("activerecord.attributes.property.operation_type")
						%th= t("activerecord.attributes.property.code")
					%tr
						%td= @property.property_type.humanize
						%td= @property.operation_type.to_s.humanize
						%td= @property.code
					%tr
						%th= t("activerecord.attributes.#{controller_name.singularize}.price")
						%th
							= t("activerecord.attributes.property.rooms") + ' / '
							= t("activerecord.attributes.property.bathrooms")
						%th= t("activerecord.attributes.#{controller_name.singularize}.size")
					%tr
						%td= @property.price
						%td= "#{@property.rooms} / #{@property.bathrooms}"
						%td= @property.size
					%tr
						%th{colspan: "6"}
							= t("activerecord.attributes.property.city") + ' / '
							= t("activerecord.attributes.property.zone")
					%tr
						%td{colspan: "6"}= "#{@property.city} / #{@property.zone}"
					%tr
						%th{colspan: "6"}= t("activerecord.attributes.#{controller_name.singularize}.reference")
					%tr
						%td{colspan: "6"}= @property.reference.to_s.humanize
					%tr
						%th{colspan: "6"}= t("activerecord.attributes.#{controller_name.singularize}.description")
					%tr
						%td{colspan: "6"}= @property.description.to_s.humanize

:javascript
	$(document).ready(function(){
		$('.slider').slider();
	});

app/views/admin/properties/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@property.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");